/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author pareg
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        label3 = new java.awt.Label();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        Inicio = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        GestionMonitor = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        GestionSocio = new javax.swing.JMenuItem();
        SocioActividad = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        GestionActividad = new javax.swing.JMenuItem();
        JMenu8 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        label3.setText("label3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión del Gimnasio \"Body Perfect\"");

        JMenu1.setText("Inicio");
        JMenu1.setActionCommand("nada");

        Inicio.setText("Volver a la página principal");
        Inicio.setActionCommand("Inicio");
        JMenu1.add(Inicio);

        jMenuBar1.add(JMenu1);

        jMenu4.setText("Monitores");

        GestionMonitor.setText("Gestión de monitores");
        GestionMonitor.setActionCommand("GestionMonitor");
        jMenu4.add(GestionMonitor);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Socios");

        GestionSocio.setText("Gestión de socios");
        GestionSocio.setActionCommand("GestionSocio");
        GestionSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionSocioActionPerformed(evt);
            }
        });
        jMenu6.add(GestionSocio);

        SocioActividad.setText("Inscripción en actividades");
        SocioActividad.setActionCommand("SocioActividad");
        jMenu6.add(SocioActividad);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Actividades");

        GestionActividad.setText("Gestión de actividades");
        GestionActividad.setActionCommand("GestionActividad");
        GestionActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionActividadActionPerformed(evt);
            }
        });
        jMenu7.add(GestionActividad);

        jMenuBar1.add(jMenu7);

        JMenu8.setText("Salir");
        JMenu8.setActionCommand("nada2");

        Salir.setText("Salir de la aplicación");
        Salir.setActionCommand("Salir");
        JMenu8.add(Salir);

        jMenuBar1.add(JMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionSocioActionPerformed

    private void GestionActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem GestionActividad;
    public javax.swing.JMenuItem GestionMonitor;
    public javax.swing.JMenuItem GestionSocio;
    public javax.swing.JMenuItem Inicio;
    public javax.swing.JMenu JMenu1;
    public javax.swing.JMenu JMenu8;
    public javax.swing.JMenuItem Salir;
    public javax.swing.JMenuItem SocioActividad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
